server:
  port: 8888
spring:
  application:
    name: visits-service
  datasource:
    url: jdbc:h2:~/testvisit
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
